#!/usr/bin/env python3
"""
统一每日汇报生成与同步脚本
用途: 汇总所有监控数据，生成统一日报，同步到飞书和本地
"""

import json
import os
import subprocess
from datetime import datetime
import sys
import traceback

# 设置日志文件
LOG_FILE = '/home/zzyuzhangxing/.openclaw/workspace/logs/daily_report.log'

def log(msg, level='INFO'):
    """记录日志"""
    timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    log_msg = f"[{timestamp}] [{level}] {msg}"
    print(log_msg)
    try:
        with open(LOG_FILE, 'a', encoding='utf-8') as f:
            f.write(log_msg + '\n')
    except:
        pass

# 飞书配置
FEISHU_WIKI_TOKEN = 'FcvTwZTTyiCZ30kNLRVchfiwnKd'
FEISHU_DOC_TOKEN = 'AZa0dcKOIo3reMxKQ2ac4OCfnwf'

# 汇报存储路径
REPORT_DIR = '/home/zzyuzhangxing/.openclaw/workspace/data/daily-reports'

def generate_daily_summary():
    """生成每日汇报摘要"""
    
    today = datetime.now().strftime('%Y-%m-%d')
    timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    
    summary = f"""# 📊 每日汇报 - {today}

> **生成时间**: {timestamp}  
> **汇报周期**: 过去24小时  
> **数据来源**: OpenClaw自动化系统

---

## 📈 数据监控总览

| 监控项 | 状态 | 数据摘要 |
|--------|------|----------|
| 🎬 B站科技区AI视频 | ✅ 已监控 | 见下方详情 |
| 👤 老鱼账号数据 | ✅ 已获取 | 见下方详情 |
| 📡 泛AI情报 | ✅ 已汇总 | 见下方详情 |
| 📚 技能学习 | ✅ 已完成 | 见下方详情 |

---

"""
    
    # 1. 加载B站账号数据
    bili_report = load_bilibili_report()
    if bili_report:
        summary += f"""## 👤 B站账号数据

{bili_report}

---

"""
    
    # 2. 加载泛AI情报
    ai_intel = load_ai_intelligence()
    if ai_intel:
        summary += f"""## 📡 泛AI情报日报

{ai_intel}

---

"""
    
    # 3. 加载技能学习记录
    skills_learned = load_skills_learned()
    if skills_learned:
        summary += f"""## 📚 今日技能学习

{skills_learned}

---

"""
    
    # 4. 推荐任务（反向提示实践）
    recommended_tasks = generate_recommended_tasks()
    summary += f"""{recommended_tasks}

---

"""
    
    # 5. 系统状态
    summary += f"""## ⚙️ 系统状态

| 组件 | 状态 |
|------|------|
| OpenClaw Gateway | ✅ 运行中 |
| 定时任务 | 10个任务正常运行 |
| 本地备份 | ✅ 已完成 |
| 飞书同步 | ⏳ 执行中 |

---

## 📝 明日关注重点

1. **观察今日热门视频后续表现** (24h数据变化)
2. **关注OpenAI/Claude/ComfyUI官方动态**
3. **准备选题脚本框架**: 从今日热点中选择跟进

---

**下次更新**: 明日 09:00  
**本地存储**: `data/daily-reports/daily_report_YYYYMMDD.md`  
**详细数据**: 见各分类目录

---

_Generated by OpenClaw WF助手 🤖_
"""
    
    return summary

def load_bilibili_report():
    """加载B站账号数据报告"""
    try:
        report_file = '/home/zzyuzhangxing/.openclaw/workspace/data/bilibili/personal/account_report_latest.md'
        if os.path.exists(report_file):
            with open(report_file, 'r', encoding='utf-8') as f:
                content = f.read()
                # 提取关键部分
                lines = content.split('\n')
                summary_lines = []
                for line in lines:
                    if line.startswith('# ') or line.startswith('## '):
                        continue
                    if '粉丝' in line or '播放' in line or '视频' in line:
                        summary_lines.append(line)
                    if len(summary_lines) > 10:
                        break
                return '\n'.join(summary_lines[:10])
    except Exception as e:
        return f"*数据加载失败: {e}*"
    return "*暂无数据*"

def load_ai_intelligence():
    """加载泛AI情报"""
    try:
        report_file = '/home/zzyuzhangxing/.openclaw/workspace/data/ai-intelligence/daily_report_latest.md'
        if os.path.exists(report_file):
            with open(report_file, 'r', encoding='utf-8') as f:
                content = f.read()
                # 提取Top 5视频
                lines = content.split('\n')
                summary_lines = []
                video_count = 0
                for line in lines:
                    if line.startswith('### ') and video_count < 5:
                        summary_lines.append(line)
                        video_count += 1
                    elif video_count > 0 and video_count <= 5 and line.strip():
                        summary_lines.append(line)
                return '\n'.join(summary_lines[:20])
    except Exception as e:
        return f"*数据加载失败: {e}*"
    return "*暂无数据*"

def load_skills_learned():
    """加载今日学习的技能"""
    try:
        log_file = '/home/zzyuzhangxing/.openclaw/workspace/skills-learning-log.json'
        if os.path.exists(log_file):
            with open(log_file, 'r', encoding='utf-8') as f:
                logs = json.load(f)
                today = datetime.now().strftime('%Y-%m-%d')
                today_logs = [l for l in logs if l.get('timestamp', '').startswith(today)]
                
                if today_logs:
                    lines = []
                    for log in today_logs[-3:]:  # 最近3个
                        skill = log.get('skillLearned', {})
                        lines.append(f"- **{log.get('hour', '?')}:00** - {skill.get('name', 'N/A')} ({log.get('category', 'N/A')})")
                    return '\n'.join(lines)
    except Exception as e:
        return f"*数据加载失败: {e}*"
    return "*今日暂无学习记录*"

def generate_recommended_tasks():
    """
    生成推荐任务 - 反向提示实践
    让OpenClaw主动思考：今天我能完成哪些任务来让老鱼更接近目标？
    """
    today = datetime.now().strftime('%Y-%m-%d')
    
    # 读取用户目标
    user_goals = """
**短期目标（3个月）:**
- B站粉丝从5万增长到8万
- 建立稳定的内容生产系统
- 每周至少发布3个高质量视频

**中期目标（1年）:**
- 创建24/7自主运营的自媒体系统
- B站粉丝突破10万
- 通过AI自媒体实现稳定收入
"""
    
    # 基于目标和当前数据生成推荐任务
    tasks = f"""### 🎯 推荐任务

> 基于老鱼的目标和当前数据，WF助手今天可以完成的任务：

**内容创作方向:**
1. 分析今日AI热门视频，生成3个选题建议
2. 基于热门趋势，编写视频脚本大纲
3. 搜索ComfyUI/Seedence最新教程，准备教程内容

**数据优化方向:**
1. 分析老鱼账号近7天视频表现，找出爆款规律
2. 监控竞品账号，学习成功案例
3. 优化标题/封面策略，提升点击率

**系统优化方向:**
1. 学习新技能（ClawHub安装）- 每小时自动执行
2. 优化早报内容，添加更多价值信息
3. 构建Mission Control任务控制中心

**立即行动:**
- [ ] 审核昨日数据，调整今日策略
- [ ] 选择1个选题，开始创作
- [ ] 测试新安装的技能

---

**💡 反向提示**: "基于我们的目标，WF助手今天还能做什么来创造更多价值？"
"""
    
    return tasks

def send_to_telegram(report_file, summary_text):
    """发送汇报到Telegram"""
    try:
        import subprocess
        result = subprocess.run(
            ['python3', 'scripts/telegram_sender.py', report_file],
            capture_output=True,
            text=True,
            cwd='/home/zzyuzhangxing/.openclaw/workspace'
        )
        log("✅ Telegram发送完成")
        return True
    except Exception as e:
        log(f"⚠️ Telegram发送失败: {e}", 'WARN')
        return False

def sync_to_feishu(content, title):
    """同步到飞书Wiki - 暂不支持，记录到日志待手动处理"""
    try:
        log(f"⏳ 飞书同步暂不支持自动写入，请手动复制到飞书")
        log(f"   目标: https://acnh7t5exjqh.feishu.cn/wiki/FcvTwZTTyiCZ30kNLRVchfiwnKd")
        
        # 记录同步日志
        sync_log = '/home/zzyuzhangxing/.openclaw/workspace/logs/feishu_sync.log'
        os.makedirs(os.path.dirname(sync_log), exist_ok=True)
        
        with open(sync_log, 'a') as f:
            f.write(json.dumps({
                'timestamp': datetime.now().isoformat(),
                'title': title,
                'status': 'manual_required',
                'target': 'daily-report-wiki',
                'note': '请手动复制报告内容到飞书Wiki'
            }) + '\n')
        
        return False  # 返回False表示需要手动处理
    except Exception as e:
        log(f"❌ 飞书同步失败: {e}", 'ERROR')
        return False

def main():
    """主函数"""
    log("=" * 60)
    log("📊 统一每日汇报生成")
    log("=" * 60)
    
    today = datetime.now().strftime('%Y-%m-%d')
    timestamp = datetime.now().strftime('%H:%M:%S')
    
    log(f"🕐 生成时间: {today} {timestamp}")
    
    # 生成汇报
    log("📝 正在生成每日汇报...")
    report = generate_daily_summary()
    
    # 保存到本地
    os.makedirs(REPORT_DIR, exist_ok=True)
    
    report_file = f"{REPORT_DIR}/daily_report_{today}.md"
    with open(report_file, 'w', encoding='utf-8') as f:
        f.write(report)
    
    log(f"✅ 本地报告已保存: {report_file}")
    
    # 保存最新报告
    latest_file = f"{REPORT_DIR}/daily_report_latest.md"
    with open(latest_file, 'w', encoding='utf-8') as f:
        f.write(report)
    
    # 同步到飞书
    log("🔄 正在同步到飞书...")
    sync_to_feishu(report, f"每日汇报 - {today}")
    
    # 发送到Telegram
    log("📱 正在发送到Telegram...")
    send_to_telegram(report_file, report[:500])
    
    # 输出摘要
    log("=" * 60)
    log("📋 汇报摘要")
    log("=" * 60)
    log(f"📅 日期: {today}")
    log(f"📁 本地文件: {report_file}")
    log(f"🔗 飞书链接: https://acnh7t5exjqh.feishu.cn/wiki/FcvTwZTTyiCZ30kNLRVchfiwnKd")
    log(f"✅ 状态: 本地已保存，飞书同步待处理")
    log("=" * 60)

if __name__ == "__main__":
    try:
        main()
        sys.exit(0)
    except Exception as e:
        log(f"❌ 日报生成异常: {e}", 'ERROR')
        traceback.print_exc()
        sys.exit(1)
