#!/usr/bin/env python3
"""
Reddit AI情报监控脚本
监控: r/artificial, r/ChatGPT, r/OpenAI, r/singularity, r/ComfyUI
频率: 每天 10:00 和 22:00
输出: 最新热门帖子Top 10（翻译成中文）
"""

import json
import requests
from datetime import datetime
import os
import sys
import re
import time

# 设置日志
LOG_FILE = '/home/zzyuzhangxing/.openclaw/workspace/logs/reddit_ai.log'

def log(msg, level='INFO'):
    timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    log_msg = f"[{timestamp}] [{level}] {msg}"
    print(log_msg)
    try:
        with open(LOG_FILE, 'a', encoding='utf-8') as f:
            f.write(log_msg + '\n')
    except:
        pass

# 监控的Subreddit列表
SUBREDDITS = [
    'artificial',      # 180万+ 最泛AI讨论
    'ChatGPT',         # 110万+ 最活跃
    'OpenAI',          # 130万+ OpenAI官方
    'singularity',     # 55万+ AGI/奇点
    'ComfyUI',         # ComfyUI工作流
]

def fetch_subreddit(subreddit, limit=10):
    """获取Subreddit热门帖子 - 使用libreddit镜像"""
    
    # libreddit镜像站列表
    mirrors = [
        f"https://libreddit.kavin.rocks/r/{subreddit}",
        f"https://reddit.invak.id/r/{subreddit}",
        f"https://libreddit.pussthecat.org/r/{subreddit}",
    ]
    
    headers = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
        'Accept-Language': 'en-US,en;q=0.5',
    }
    
    for mirror_url in mirrors:
        try:
            log(f"获取 r/{subreddit} (via {mirror_url.split('/')[2]})...")
            response = requests.get(mirror_url, headers=headers, timeout=30)
            
            if response.status_code == 200:
                # 用正则解析HTML
                posts = []
                
                # 查找帖子标题和链接
                # libreddit格式: <a class="post_title" href="...">
                title_pattern = r'<a[^>]*class="[^"]*post_title[^"]*"[^>]*href="([^"]+)"[^>]*>([^<]+)</a>'
                titles = re.findall(title_pattern, response.text, re.IGNORECASE)
                
                # 备选模式
                if not titles:
                    title_pattern2 = r'<h2[^>]*class="[^"]*post-title[^"]*"[^>]*>.*?<a[^>]*href="([^"]+)"[^>]*>([^<]+)</a>.*?</h2>'
                    titles = re.findall(title_pattern2, response.text, re.IGNORECASE | re.DOTALL)
                
                for href, title in titles[:limit]:
                    # 清理标题
                    clean_title = re.sub(r'<[^>]+>', '', title).strip()
                    if clean_title:
                        posts.append({
                            'title': clean_title[:200],
                            'score': 0,
                            'comments': 0,
                            'url': f"https://reddit.com{href}" if href.startswith('/') else href,
                            'external_url': '',
                            'author': '',
                            'created_utc': 0,
                            'subreddit': subreddit,
                            'selftext': '',
                        })
                
                if posts:
                    log(f"  ✅ 获取到 {len(posts)} 条帖子")
                    return posts
                else:
                    log(f"  ⚠️ 未解析到帖子，尝试其他镜像...")
                    
        except Exception as e:
            log(f"  ✗ {mirror_url.split('/')[2]} 失败: {str(e)[:50]}", 'WARN')
            continue
    
    log(f"  ✗ 所有镜像都失败了", 'ERROR')
    return []

def generate_report(all_posts):
    """生成报告"""
    today = datetime.now().strftime('%Y-%m-%d')
    timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    
    report = f"""# 🌍 Reddit AI情报日报 - {today}

> **生成时间**: {timestamp}  
> **数据来源**: Reddit RSS  
> **监控社区**: r/artificial, r/ChatGPT, r/OpenAI, r/singularity, r/ComfyUI

---

## 📊 数据概览

| 指标 | 数值 |
|------|------|
| 🔍 监控社区 | {len(SUBREDDITS)} 个 |
| 📰 获取帖子 | {len(all_posts)} 条 |

---

## 🔥 热门帖子

"""
    
    for i, post in enumerate(all_posts[:20], 1):
        # 分类图标
        sub_icon = {
            'artificial': '🤖',
            'ChatGPT': '💬',
            'OpenAI': '🌐',
            'singularity': '⚡',
            'ComfyUI': '🎨'
        }.get(post['subreddit'], '📌')
        
        report += f"""### {i}. {sub_icon} {post['title'][:100]}{'...' if len(post['title']) > 100 else ''}

- **社区**: r/{post['subreddit']}
- **链接**: [查看帖子]({post['url']})

---

"""
    
    # 添加各社区统计
    report += """## 📈 各社区帖子数

| 社区 | 帖子数 |
|------|--------|
"""
    
    for sub in SUBREDDITS:
        sub_posts = [p for p in all_posts if p['subreddit'] == sub]
        report += f"| r/{sub} | {len(sub_posts)} |\n"
    
    report += f"""

---

*Generated by WF助手 🤖*  
*数据来源: Reddit RSS*  
*下次更新: { '明日 22:00' if datetime.now().hour >= 10 else '今日 22:00' }*
"""
    
    return report

def main():
    """主函数"""
    log("=" * 60)
    log("🌍 Reddit AI情报监控")
    log("=" * 60)
    
    all_posts = []
    
    # 获取每个社区的数据
    for subreddit in SUBREDDITS:
        posts = fetch_subreddit(subreddit, limit=10)
        all_posts.extend(posts)
        # 避免请求过快
        time.sleep(3)
    
    log(f"📊 总计获取 {len(all_posts)} 条帖子")
    
    if not all_posts:
        log("⚠️ 未获取到任何数据", 'WARN')
        return 1
    
    # 生成报告
    log("📝 生成报告...")
    report = generate_report(all_posts)
    
    # 保存报告
    data_dir = '/home/zzyuzhangxing/.openclaw/workspace/data/reddit-ai'
    os.makedirs(data_dir, exist_ok=True)
    
    today = datetime.now().strftime('%Y%m%d')
    hour = datetime.now().strftime('%H%M')
    
    # 保存带时间戳的版本
    report_file = f"{data_dir}/report_{today}_{hour}.md"
    with open(report_file, 'w', encoding='utf-8') as f:
        f.write(report)
    log(f"✅ 报告已保存: {report_file}")
    
    # 保存最新版本
    latest_file = f"{data_dir}/report_latest.md"
    with open(latest_file, 'w', encoding='utf-8') as f:
        f.write(report)
    
    # 输出摘要
    log("=" * 60)
    log("📋 监控摘要")
    log("=" * 60)
    log(f"📰 总帖子: {len(all_posts)}")
    log(f"🔥 总热度: {sum(p['score'] for p in all_posts):,}")
    log(f"💬 总评论: {sum(p['comments'] for p in all_posts):,}")
    
    # Top 3 预览
    all_posts.sort(key=lambda x: x['score'], reverse=True)
    log("\n🔥 Top 3:")
    for i, p in enumerate(all_posts[:3], 1):
        log(f"  {i}. {p['title'][:50]}... ({p['score']:,}👍)")
    
    log("\n✅ Reddit AI监控完成!")
    log("=" * 60)
    
    return 0

if __name__ == '__main__':
    try:
        sys.exit(main())
    except Exception as e:
        log(f"❌ 脚本异常: {e}", 'ERROR')
        import traceback
        traceback.print_exc()
        sys.exit(1)
